[package]
name = "wakatime-lsp"
version = "0.1.0"
edition = "2021"

description = "A dead-simple LSP around wakatime-cli to send code tracking heartbeats"
repository = "https://github.com/mrnossiom/wakatime-lsp"
keywords = ["lsp", "wakatime"]
categories = ["development-tools"]
license = "CECILL-2.1"

[dependencies]
serde_json = "1.0.114"
tokio = { version = "1.37.0", features = ["io-std", "macros", "process", "rt"] }
tower-lsp = "0.20.0"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[lints]
[lints.clippy]
pedantic = "warn"
nursery = "warn"
# cargo = "warn"

dbg_macro = "warn"
missing_docs_in_private_items = "warn"
todo = "warn"
unwrap_used = "warn"
[lints.rustdoc]
all = "warn"
